site_name: CPS1 Official Documentation
site_url: https://docs.cps1.tech/
copyright: Copyright &copy; 2025 CPS1 Tecnologia LTDA
theme:
  name: material
  palette:
    primary: black
  logo: assets/images/cps1-logo.png
  favicon: assets/images/favicon.ico
  custom_dir: overrides
  collapse:
    navigation: false
  features:
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - content.code.annotate
    - navigation.instant
    - navigation.footer
    - content.code.copy

draft_docs: |
  drafts/

plugins:
  - social

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Welcome to CPS1: index.md
  - Introduction:
    - What is CPS1?: what-is-cps1.md
    - How CPS1 fits into your workflow: how-cps1-fits-workflow.md
    - Key Concepts: key-concepts.md
    - Architecture Overview: architecture-overview.md
    - Quickstart Guide: quickstart.md
  - Installation:
    - Production Installation: installation/production-installation.md
  - Configuration:
    - Git Repository Integration: git-repository-integration.md
    - User management: user-management.md
    - Licensing: licensing.md

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://br.linkedin.com/company/cps1
      name: CPS1 on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/cps-1
      name: CPS1 on GitHub
  analytics:
    provider: google
    property: G-FFD1PCEGF1
  version:
    provider: mike
